version: '3.5'
networks:
  chautari:
    name: backend_chautari

services:
    finder:
        image: chautari
        build: .
        restart: always
        command: bash -c "/usr/wait-for-it.sh --timeout=0 db:5432 && _build/prod/rel/finder/bin/finder eval 'Finder.Release.migrate' &&  _build/prod/rel/finder/bin/finder eval 'Finder.Release.seed' &&  _build/prod/rel/finder/bin/finder start"
        container_name: finder_api
        depends_on:
          - db
        environment: 
          DATABASE_URL:  ecto://deploy:P@ssword@db/finder
          SECRET_KEY_BASE: GYjWGHDHDe3Ob+Qivj7NBPP+8FU429wAJrVl9XWM78lXLpZ/2HcTKuc5BJ+hPvpq

          DATABASE_HOST: db
          USER: deploy
          PASSWORD: P@ssword
          DATABASE: finder_dev
          DIALECT: 'postgres'
          PORT: 4000
        ports:
          - 4000:4000
        networks:
          - chautari
        # volumes:
          # - /opt/finder/uploads:/live/finder/uploads

    db:
        restart: always
        image: postgres:13.1
        ports:
        - 5432:5432
        container_name: finder_db
        networks:
          - chautari
        environment: 
           POSTGRES_USER: deploy
           POSTGRES_PASSWORD: P@ssword
           POSTGRES_DB: finder
           POSTGRES_HOSTNAME: localhost
           POSTGRES_POOLSIZE: 10
        # volumes:
          # - /tmp/.s.PGSQL.5432:/var/run/postgresql/.s.PGSQL.5432
        # volumes:
        #   - /opt/roomfinder/mysql_dump:/docker-echautarirypoichautari-initdb.d
        #   - /opt/roomfinder/mysql:/var/lib/mysql

    adminer:
      image: adminer
      restart: always
      hostname: finder-database-server
      container_name: finder_adminer
      networks:
        - chautari
      ports:
        - 8080:8080